# Generated by Django 2.0 on 2018-10-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_efecto', models.CharField(max_length=50)),
                ('descripcion_efecto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionPedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pedal', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('descripcion_pedal', models.CharField(max_length=1000)),
                ('imgPedal', models.ImageField(blank=True, upload_to='static/img')),
                ('urlVideo', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField()),
                ('precio', models.FloatField()),
                ('fecha_publicacion', models.DateField()),
                ('autor_publicacion', models.CharField(max_length=50)),
                ('evaluada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('efecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainCatalogo.Efecto')),
            ],
        ),
    ]
