# Generated by Django 2.0 on 2018-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionpedal',
            name='puntuacion',
            field=models.FloatField(default=0),
        ),
    ]
