# Generated by Django 2.0 on 2018-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0002_auto_20181027_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionpedal',
            name='imgPedal',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
