# Generated by Django 2.0 on 2018-10-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0004_auto_20181027_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionpedal',
            name='urlVideo',
        ),
        migrations.AddField(
            model_name='publicacionpedal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
