# Generated by Django 2.0 on 2018-10-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0005_auto_20181027_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionpedal',
            name='imgPedal',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
