# Generated by Django 2.0 on 2018-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0006_auto_20181027_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionpedal',
            name='imgPedal',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
