# Generated by Django 2.0 on 2018-10-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0007_auto_20181027_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionpedal',
            name='imgPedal',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='publicacionpedal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
