# Generated by Django 2.0 on 2018-10-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCatalogo', '0008_auto_20181027_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionpedal',
            name='imgPedal',
        ),
        migrations.AddField(
            model_name='publicacionpedal',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='publicacionpedal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/video/'),
        ),
    ]
